language: c

compiler:
  - gcc
  - clang

before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-syscommand/build_config.rb .

script: 
  - make all
